production:
  username: your@email.com
  password: yourpassword
  app_token: yourtoken
  domain: opendata.socrata.com
  dataset: 38fr-xg2g
  batch_size: 30
  check_time: 5
  stuck_time: 15
  feed_url: "http://bitly.measuredvoice.com/usa.gov"

production:
  username: your@email.com
  password: yourpassword
  app_token: yourtoken
  domain: opendata.socrata.com
  dataset: 38fr-xg2g
  batch_size: 30
  check_time: 5
  stuck_time: 15
  feed_url: "http://bitly.measuredvoice.com/usa.gov"
